const ICONS = {
  hp: "HP",
  thirst: "SU",
  hunger: "AC",
  morale: "MO",
  raft: "SAL",
  crew: "T",
  load: "KG",
  water: "SD",
  seed: "#",
  time: "T",
  speed: ">",
  weather: "H",
  sea: "~",
  lower: "A",
  raftLayer: "O",
  moduleLayer: "U",
  move: "<>",
  delete: "X",
  back: "<",
  plank: "P",
  beam: "K",
  net: "N",
  crabTrap: "YK",
  waterCollector: "ST",
  grill: "OC",
  chest: "S",
  bed: "Y",
  mast: "D",
  sail: "Y",
  center: "C",
  build: "+"
};

const ASSET_ICONS = {
  hp: "/assets/ui/hud/hp.png",
  thirst: "/assets/ui/hud/thirst.png",
  hunger: "/assets/ui/hud/hunger.png",
  morale: "/assets/ui/hud/morale.png",
  raft: "/assets/ui/hud/raft.png",
  crew: "/assets/ui/hud/crew.png",
  load: "/assets/ui/hud/load.png",
  water: "/assets/ui/hud/water-reserve.png",
  seed: "/assets/ui/hud/seed.png",
  time: "/assets/ui/hud/time.png",
  speed: "/assets/ui/hud/speed.png",
  wind: "/assets/ui/hud/wind.png",
  plank: "/assets/ui/raft/plank.png",
  beam: "/assets/ui/raft/beam.png",
  net: "/assets/ui/raft/net.png",
  crabTrap: "/assets/ui/raft/net.png",
  waterCollector: "/assets/ui/raft/water-collector.png",
  grill: "/assets/ui/raft/grill.png",
  chest: "/assets/ui/raft/chest.png",
  forge: "/assets/ui/raft/forge.png",
  waterDist: "/assets/ui/raft/water-dist.png",
  bed: "/assets/ui/raft/bed.png",
  mast: "/assets/ui/raft/mast.png",
  sail: "/assets/ui/raft/sail.png",
  menu: "/assets/ui/menu/menu.png",
  craft: "/assets/ui/menu/craft.png",
  inventory: "/assets/ui/menu/inventory.png",
  map: "/assets/ui/menu/map.png",
  fishing: "/assets/ui/menu/fishing.png",
  dive: "/assets/ui/menu/dive.png",
  system: "/assets/ui/menu/system.png",
  save: "/assets/ui/menu/save.png",
  loadGame: "/assets/ui/menu/load.png",
  fullscreen: "/assets/ui/menu/fullscreen.png",
  back: "/assets/ui/menu/back.png",
  anchorUp: "/assets/ui/menu/anchor-up.png",
  anchorDown: "/assets/ui/menu/anchor-down.png",
  enter: "/assets/ui/menu/enter.png",
  attack: "/assets/ui/menu/attack.png",
  repair: "/assets/ui/menu/repair.png",
  weatherSunny: "/assets/ui/hud/weather-sunny.png",
  weatherCloudy: "/assets/ui/hud/weather-cloudy.png",
  weatherRain: "/assets/ui/hud/weather-rain.png",
  weatherStorm: "/assets/ui/hud/weather-storm.png",
  seaCalm: "/assets/ui/hud/sea-calm.png",
  seaChoppy: "/assets/ui/hud/sea-choppy.png",
  seaRough: "/assets/ui/hud/sea-rough.png"
};

export function iconMarkup(name, extraClass = "") {
  if (ASSET_ICONS[name]) {
    return `<img class="game-icon game-icon-asset icon-${name} ${extraClass}" src="${ASSET_ICONS[name]}" alt="" draggable="false">`;
  }
  const glyph = ICONS[name] ?? "?";
  return `<span class="game-icon icon-${name} ${extraClass}" aria-hidden="true">${glyph}</span>`;
}
